micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/nossa-casa-do-codigo?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    schema-generate: CREATE_DROP
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
